controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    omni_wheel_velocity_controller:
      type: forward_command_controller/ForwardCommandController

    left_arm_position_controller:
      type: forward_command_controller/ForwardCommandController

    left_gripper_position_controller:
      type: forward_command_controller/ForwardCommandController

    right_arm_position_controller:
      type: forward_command_controller/ForwardCommandController

    right_gripper_position_controller:
      type: forward_command_controller/ForwardCommandController

    head_position_controller:
      type: forward_command_controller/ForwardCommandController

omni_wheel_velocity_controller:
  ros__parameters:
    interface_name: velocity
    joints:
      - wheel_0_joint
      - wheel_1_joint
      - wheel_2_joint

left_arm_position_controller:
  ros__parameters:
    interface_name: position
    joints:
      - Rotation
      - Pitch
      - Elbow
      - Wrist_Pitch
      - Wrist_Roll

left_gripper_position_controller:
  ros__parameters:
    interface_name: position
    joints:
      - Jaw

right_arm_position_controller:
  ros__parameters:
    interface_name: position
    joints:
      - Rotation_2
      - Pitch_2
      - Elbow_2
      - Wrist_Pitch_2
      - Wrist_Roll_2

right_gripper_position_controller:
  ros__parameters:
    interface_name: position
    joints:
      - Jaw_2

head_position_controller:
  ros__parameters:
    interface_name: position
    joints:
      - head_pan_joint
      - head_tilt_joint
